### ISSUE TITLE
[feat] 음성파일, 텍스트 저장 API

### ISSUE THREAD

**Issue by k0000k** [COOING-team/COOING-Server#1]
## Description
음성 저장과 최종 텍스트를 받는 API를 개발합니다.

## To-do
- [x] 음성 파일 저장 API
- [x] 최종 텍스트와 음성파일 URL 받는 API 
- [ ] 스프링 시큐리티 설정 추가

## ETC
- 예상 마감: 2023/11/05
