### ISSUE TITLE
[Fix] 익셉션 처리 안된거 

### ISSUE THREAD

**Issue by HI-JIN2** [COOING-team/COOING-Server#31]
## Description
커스텀 익셉션 추가

## To-do
- [x] 홈에서 아이 없을때
- [x] 답변 기록하기 에서 질문 없을때
- [x] 답변 기록하기 에서 아이 없을떄 

## ETC
- 예상 마감: 1204
